export enum TypeMicrodata {
  AVALIACAO = 'AVALIACAO',
  AVALIACAO_NORMALIZADA = 'AVALIACAO_NORMALIZADA',
  ALUNOS = 'ALUNOS',
  INFREQUENCIA = 'INFREQUENCIA',
  TEMPLATE_AVALIACAO = 'TEMPLATE_AVALIACAO',
}
