export const selectDefaultReportSubject = [
  'REPORT_SUBJECT.testTESID testId',
  'REPORT_SUBJECT.type as type',
  'REPORT_SUBJECT.name as subject',
  'SUM(REPORT_SUBJECT.countTotalStudents) as countTotalStudents',
  'SUM(REPORT_SUBJECT.countStudentsLaunched) as countStudentsLaunched',
  'SUM(REPORT_SUBJECT.totalGradesStudents) as totalGradesStudents',
  'SUM(REPORT_SUBJECT.countPresentStudents) as countPresentStudents',
  'SUM(REPORT_SUBJECT.fluente) as fluente',
  'SUM(REPORT_SUBJECT.nao_fluente) as nao_fluente',
  'SUM(REPORT_SUBJECT.frases) as frases',
  'SUM(REPORT_SUBJECT.palavras) as palavras',
  'SUM(REPORT_SUBJECT.silabas) as silabas',
  'SUM(REPORT_SUBJECT.nao_leitor) as nao_leitor',
  'SUM(REPORT_SUBJECT.nao_avaliado) as nao_avaliado',
  'SUM(REPORT_SUBJECT.nao_informado) as nao_informado',
]

export const selectDefaultReportNotEvaluated = [
  'REPORT_NOT_EVALUATED.testTESID as testId',
  'REPORT_NOT_EVALUATED.type as type',
  'REPORT_NOT_EVALUATED.name as subject',
  'SUM(REPORT_NOT_EVALUATED.countTotalStudents) as countTotalStudents',
  'SUM(REPORT_NOT_EVALUATED.countStudentsLaunched) as countStudentsLaunched',
  'SUM(REPORT_NOT_EVALUATED.countPresentStudents) as countPresentStudents',
  'SUM(REPORT_NOT_EVALUATED.recusa) as recusa',
  'SUM(REPORT_NOT_EVALUATED.ausencia) as ausencia',
  'SUM(REPORT_NOT_EVALUATED.abandono) as abandono',
  'SUM(REPORT_NOT_EVALUATED.transferencia) as transferencia',
  'SUM(REPORT_NOT_EVALUATED.deficiencia) as deficiencia',
  'SUM(REPORT_NOT_EVALUATED.nao_participou) as nao_participou',
]

export const selectDefaultReportRace = [
  'REPORT_RACE.racePELID as PEL_ID',
  'REPORT_RACE.name as name',
  'SUM(REPORT_SUBJECT.totalGradesStudents) as totalGradesStudentsSubject',
  'SUM(REPORT_SUBJECT.countPresentStudents) as countPresentStudentsSubject',
  'SUM(REPORT_RACE.countTotalStudents) as countTotalStudents',
  'SUM(REPORT_RACE.countPresentStudents) as countPresentStudents',
  'SUM(REPORT_RACE.totalGradesStudents) as totalGradesStudents',
  'SUM(REPORT_RACE.fluente) as fluente',
  'SUM(REPORT_RACE.nao_fluente) as nao_fluente',
  'SUM(REPORT_RACE.frases) as frases',
  'SUM(REPORT_RACE.palavras) as palavras',
  'SUM(REPORT_RACE.silabas) as silabas',
  'SUM(REPORT_RACE.nao_leitor) as nao_leitor',
  'SUM(REPORT_RACE.nao_avaliado) as nao_avaliado',
  'SUM(REPORT_RACE.nao_informado) as nao_informado',
]

export const selectDefaultReportQuestion = [
  'report_question.option_correct as option_correct',
  'report_question.questionTEGID as questionId',
  'SUM(report_question.total_a) as total_a',
  'SUM(report_question.total_b) as total_b',
  'SUM(report_question.total_c) as total_c',
  'SUM(report_question.total_d) as total_d',
  'SUM(report_question.total_null) as total_null',
  'SUM(report_question.fluente) as fluente',
  'SUM(report_question.nao_fluente) as nao_fluente',
  'SUM(report_question.frases) as frases',
  'SUM(report_question.palavras) as palavras',
  'SUM(report_question.silabas) as silabas',
  'SUM(report_question.nao_leitor) as nao_leitor',
  'SUM(report_question.nao_avaliado) as nao_avaliado',
  'SUM(report_question.nao_informado) as nao_informado',
]
