INSERT INTO `PERFIL_BASE` (`PER_ID`, `PER_NOME`, `PER_ATIVO`) VALUES (1, 'SAEV', '1');
INSERT INTO `PERFIL_BASE` (`PER_ID`, `PER_NOME`, `PER_ATIVO`) VALUES (2, 'Escola', '1');
INSERT INTO `PERFIL_BASE` (`PER_ID`, `PER_NOME`, `PER_ATIVO`) VALUES (3, 'Município', '1');
