INSERT INTO `RACA` (`PEL_ID`, `PEL_NOME`, `PEL_ATIVO`, `PEL_OLD_ID`) VALUES (1, 'Branca', '1', 1);
INSERT INTO `RACA` (`PEL_ID`, `PEL_NOME`, `PEL_ATIVO`, `PEL_OLD_ID`) VALUES (2, 'Parda', '1', 2);
INSERT INTO `RACA` (`PEL_ID`, `PEL_NOME`, `PEL_ATIVO`, `PEL_OLD_ID`) VALUES (3, 'Preta', '1', 3);
INSERT INTO `RACA` (`PEL_ID`, `PEL_NOME`, `PEL_ATIVO`, `PEL_OLD_ID`) VALUES (5, 'Amarela (Oriental)', '1', 5);
INSERT INTO `RACA` (`PEL_ID`, `PEL_NOME`, `PEL_ATIVO`, `PEL_OLD_ID`) VALUES (9, 'Indígena', '1', 9);
INSERT INTO `RACA` (`PEL_ID`, `PEL_NOME`, `PEL_ATIVO`, `PEL_OLD_ID`) VALUES (17, 'Não desejo informar', '1', 17);
INSERT INTO `RACA` (`PEL_ID`, `PEL_NOME`, `PEL_ATIVO`, `PEL_OLD_ID`) VALUES (18, 'Não desejo informar', '1', 0);
